# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d326f892115f0a7dc0094a72019199702c0f9355b94d9f225bf0d654be351aa01288ee5978df4b7f2585133f4bb17b9cbe8d8011c1a43a5b0a3eb82c1eac2245

test:
  secret_key_base: 024fd8f1235f11367f0366ac460ab38c57a9b6d03809380640beea93eab728690388e80038b30587afaa30ddf0a37879430227c42c0c2015702a884fc65186f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
